
package com.restclient.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAgeMessage", targetNamespace = "http://webservice.com/", className = "com.webservice.GetAgeMessage")
    @ResponseWrapper(localName = "getAgeMessageResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.GetAgeMessageResponse")
    public String getAgeMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://webservice.com/", className = "com.webservice.GetMessage")
    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://webservice.com/", className = "com.webservice.GetMessageResponse")
    public String getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
